"""
Explanation generator for VERA.

Converts risk flags and scores into plain-language text that a non-technical
reviewer can understand. Language is carefully hedged to avoid implying
guilt or confirmed wrongdoing.

Vocabulary guidelines:
  ✓ "Potential risk indicator detected"
  ✓ "Review recommended"
  ✓ "Statistically unusual"
  ✓ "Requires additional verification"
  ✗ "Fraud detected"
  ✗ "Corrupt"
  ✗ "Automatically rejected"
"""
from __future__ import annotations

_LEVEL_INTRO = {
    "High": (
        "AI Assessment: This submission contains multiple potential risk indicators "
        "that warrant priority human verification before proceeding."
    ),
    "Medium": (
        "AI Assessment: This submission contains one or more anomalies that may "
        "require additional verification."
    ),
    "Low": (
        "AI Assessment: No significant anomalies were detected. "
        "Standard review is recommended."
    ),
}

_DISCLAIMER = (
    "\n\nImportant: These indicators are generated by an AI system and represent "
    "potential areas of concern only. They do not constitute evidence of fraud, "
    "corruption, or any wrongdoing. The final decision rests with the human reviewer."
)


def generate_explanation(
    risk_level: str,
    risk_score: float,
    flags: list[dict],
) -> str:
    """
    Build a complete human-readable explanation from risk level and flags.
    """
    intro = _LEVEL_INTRO.get(risk_level, _LEVEL_INTRO["Low"])
    lines = [intro, ""]

    if flags:
        lines.append("Potential risk indicators identified:")
        for flag in flags:
            severity_label = {
                "high": "⚠ High",
                "medium": "◆ Medium",
                "low": "• Low",
            }.get(flag.get("severity", "low"), "•")
            lines.append(f"  {severity_label} — {flag['label']}")
        lines.append("")
        lines.append(
            f"Risk Score: {risk_score:.0f} / 100  ({risk_level} Priority)"
        )
    else:
        lines.append(
            "No rule-based anomalies were triggered. "
            "The AI model also found no statistically unusual patterns."
        )

    lines.append("")
    lines.append("Recommended Action:")
    if risk_level == "High":
        lines.append(
            "Human verification required. Review all flagged indicators before "
            "approving or rejecting this submission."
        )
    elif risk_level == "Medium":
        lines.append(
            "Additional verification recommended. Confirm flagged items with "
            "supporting documentation."
        )
    else:
        lines.append(
            "No immediate action required beyond standard review procedures."
        )

    lines.append(_DISCLAIMER)
    return "\n".join(lines)
